/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FlightBooking } from "./FlightBooking";
export * as factories from "./factories";
export { FlightBooking__factory } from "./factories/FlightBooking__factory";
